### ISSUE TITLE
push checks to see if $notifiable is an array

### ISSUE THREAD

**Issue by csuarezgfx** [michaeljennings/feed#1]
Unfortunately, I am feeding it a Collection of users. So I altered:

```
if ( ! is_array($notifiable) ) {
        $notifiable = [$notifiable];
}
```

to:

```
if ((! is_array($notifiable)) && ! ($notifiable instanceof Collection)) {
    $notifiable = [$notifiable];
}
``
```

**Comment by michaeljennings** [comment]
Good spot! I've changed your solution slightly by checking if the notifiable class is traversable. This will just check that it is a class that can go through a loop. This should be fixed in the v0.1.3. Let me know if you're still having issues with it.

**Comment by csuarezgfx** [comment]
Hi 
`$notifiable instanceof Traversable`
produces previous error, changed to:
`$notifiable instanceof \Traversable`

**Comment by michaeljennings** [comment]
Hi have you pulled in the latest update? I believe I used the Traversable interface at the top so that should be working? If it's not let me know and I'll fix it.
