### ISSUE TITLE
Argument 1 passed to Michaeljennings\Feed\Events\NotificationAdded::__construct() must implement interface

### ISSUE THREAD

**Issue by Sharadcosmonaut** [michaeljennings/feed#5]
I have isssue : Please check Link : https://prnt.sc/k8qdzs

**Comment by michaeljennings** [comment]
Which version of laravel are you using? To be honest I've been using the laravel notifications since they were added in laravel 5.3.

It looks to me like you're passing it's creating an instance of the laravel notification, can you add some example code for me to be able to recreate the issue?

**Comment by Sharadcosmonaut** [comment]
I have using laravel 5.6.

This is my User.php
`<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Michaeljennings\Feed\Contracts\Notifiable as NotifiableContract;
// use Michaeljennings\Feed\Notifications\Notifiable;

class User extends Authenticatable implements NotifiableContract
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */

    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */

    protected $hidden = [
        'password', 'remember_token',
    ];
}`

This is my main Controller "TestController.php"

`<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use App\User;
use App\Team;
use Michaeljennings\Feed\Contracts\Notifiable as NotifiableContract;
use Michaeljennings\Feed\Notifications\Notifiable;

class TestController extends Controller
{
    
    public function __construct()
    {
		    	
    }

	public function index(){
		$feed = feed();
		$user = User::find(1);

		// $team = Team::find(1);
		// print_r($team);
		// exit;
		// Push notification to a user
		$userId = $user->id;
		// $feed->push('This is a new notification',$user);

		// Push notification to a user, and a team of users
		//$feed->push('This is a new notification', [$user, $team]);

		// Push notification to a user with multiple parameters
		$feed->push([
		    'icon' => 'icon-alert',
		    'title' => 'Something Broke!',
		    'body' => 'Something super important broke'
		], $user);

		// Get all of the notifications for a user
		// $notifications = $feed->pull($user);

		// Get 10 notifications for the user
		// $notifications = $feed->limit(10)->pull($user);
		// print_r($notifications);
		// exit;

		// Mark a notification as read
		// $feed->markAsRead($notification);
	}

}
`

**Comment by michaeljennings** [comment]
In your user model you are implementing the wrong notifiable trait, you should be using the `MichaelJennings\Feed\Notifications\Notifiable' trait instead.

```php
`<?php

namespace App;

// use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Michaeljennings\Feed\Contracts\Notifiable as NotifiableContract;
use Michaeljennings\Feed\Notifications\Notifiable;

class User extends Authenticatable implements NotifiableContract
{
use Notifiable;

/**
 * The attributes that are mass assignable.
 *
 * @var array
 */

protected $fillable = [
    'name', 'email', 'password',
];

/**
 * The attributes that should be hidden for arrays.
 *
 * @var array
 */

protected $hidden = [
    'password', 'remember_token',
];
}
```

To be honest if you are using laravel 5.6 I'd recommend using the default [laravel notifications](https://laravel.com/docs/5.6/notifications) as I no longer support this package and the laravel notifications offer all of the same functionality. 

I've run the tests and the are working on every version of laravel 5+ so it should in theory work in 5.6 if you do want to continue using it.

I'm going to update the docs to indicate that this package is abandoned.
